### ISSUE TITLE
Cookies not set

### ISSUE THREAD

**Issue by iamlasse** [codeliter/docker-compose-caddy-laravel#1]
Hi, I just tested your setup and although it works smoothly to start, when I try to login to a user after seeding, I get page expired, and no cookies are set in the browser. Is this a caddy issue or something I've forgotten to set?

**Comment by codeliter** [comment]
@iamlasse, let me confirm this. In the meantime, it would help if I could see the content of your `docker-composer.yml`, `composer.json` and the syntax used for setting the cookie.

**Comment by codeliter** [comment]
Everything looks fine from my test. I  tested by setting a cookie this way: 
```php
$cookie = cookie('steve', '12', 10);
``` 
and I tested it by sending the response to the frontend this way:

```php
    response()->json([
        'cookie'=>$_COOKIE,
    ])->withCookie($cookie);
```

**Comment by iamlasse** [comment]
I tried a fresh install with Jetstream instead of my app and it worked.

**Comment by codeliter** [comment]
Happy to know it is working now!

**Comment by iamlasse** [comment]
For anyone having a similar issue, the solution is to clear config eg php artisan config:cache or config:cl as well as php artisan cache:cl after that it should work.
