### ISSUE TITLE
Storage link doesn't seem to work

### ISSUE THREAD

**Issue by iamlasse** [codeliter/docker-compose-caddy-laravel#2]
Hi, I'm back with another issue. I tried using the docker-compose run --rm app php artisan storage:link to link storage but it won't work for some reason. Do you have any suggestions for this? Did it just work for you or was there a workaround?

**Comment by codeliter** [comment]
@iamlasse, Were you able to get this working?

**Comment by iamlasse** [comment]
Hey, yes it may have been a rookie mistake but i got it going with —relative and changing the app url env setting :)
